### ISSUE TITLE
etils TypeError

### ISSUE THREAD

**Issue by rjd55** [dattalab/keypoint-moseq#132]
Hi, I've installed this conda environment:
# Linux (GPU)
conda env create -f conda_envs/environment.linux_gpu.yml
and I am getting an error this error message:

Loading conda 4.10.3...
Traceback (most recent call last):
  File "/data/users/rebdoche/Documents/home-cage-analysis-system/External/keypoint-moseq/evomoseq.py", line 1, in <module>
    import keypoint_moseq as kpms
  File "/data/users/rebdoche/Documents/home-cage-analysis-system/External/keypoint-moseq/keypoint_moseq/__init__.py", line 2, in <module>
    from jax import config
  File "/data/users/rebdoche/conda/envs/keypoint_moseq/lib/python3.9/site-packages/jax/__init__.py", line 63, in <module>
    from jax._src.api import (
  File "/data/users/rebdoche/conda/envs/keypoint_moseq/lib/python3.9/site-packages/jax/_src/api.py", line 48, in <module>
    from jax._src import callback as jcb
  File "/data/users/rebdoche/conda/envs/keypoint_moseq/lib/python3.9/site-packages/jax/_src/callback.py", line 26, in <module>
    from jax._src import dispatch
  File "/data/users/rebdoche/conda/envs/keypoint_moseq/lib/python3.9/site-packages/jax/_src/dispatch.py", line 58, in <module>
    from etils import epath
  File "/data/users/rebdoche/conda/envs/keypoint_moseq/lib/python3.9/site-packages/etils/epath/__init__.py", line 19, in <module>
    from etils.epath import testing
  File "/data/users/rebdoche/conda/envs/keypoint_moseq/lib/python3.9/site-packages/etils/epath/testing.py", line 27, in <module>
    from etils.epath import gpath
  File "/data/users/rebdoche/conda/envs/keypoint_moseq/lib/python3.9/site-packages/etils/epath/gpath.py", line 29, in <module>
    from etils import epy
  File "/data/users/rebdoche/conda/envs/keypoint_moseq/lib/python3.9/site-packages/etils/epy/__init__.py", line 22, in <module>
    from etils.epy.binary_import import binary_adhoc
  File "/data/users/rebdoche/conda/envs/keypoint_moseq/lib/python3.9/site-packages/etils/epy/binary_import.py", line 55, in <module>
    restrict: None | py_utils.StrOrStrList = None,
TypeError: unsupported operand type(s) for |: 'NoneType' and '_UnionGenericAlias'

Should I use a different version of etils than what is currently in the `yml` file?

**Comment by calebweinreb** [comment]
Thanks for posting an issue! I just updated the env file to deal with this (https://github.com/dattalab/keypoint-moseq/commit/a3c569381dc1ce8040dce1afd6ac7ddc945ce187)

You could update the etils version to 1.5.2 in your existing env, or start over with the new env file.
