### ISSUE TITLE
Problem with launching jupyter notebook in anaconda prompt or navigator 

### ISSUE THREAD

**Issue by eva10j** [dattalab/keypoint-moseq#141]
Traceback (most recent call last):
  File "C:\Users\evaji\anaconda3\envs\keypoint_moseq\lib\site-packages\requests\compat.py", line 11, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\evaji\anaconda3\envs\keypoint_moseq\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\evaji\anaconda3\envs\keypoint_moseq\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\evaji\anaconda3\envs\keypoint_moseq\Scripts\jupyter-notebook.EXE\__main__.py", line 4, in <module>
    from notebook.app import main
  File "C:\Users\evaji\anaconda3\envs\keypoint_moseq\lib\site-packages\notebook\app.py", line 20, in <module>
    from jupyterlab.commands import (  # type:ignore[import-untyped]
  File "C:\Users\evaji\anaconda3\envs\keypoint_moseq\lib\site-packages\jupyterlab\__init__.py", line 8, in <module>
    from .handlers.announcements import (
  File "C:\Users\evaji\anaconda3\envs\keypoint_moseq\lib\site-packages\jupyterlab\handlers\announcements.py", line 15, in <module>
    from jupyterlab_server.translation_utils import translator
  File "C:\Users\evaji\anaconda3\envs\keypoint_moseq\lib\site-packages\jupyterlab_server\__init__.py", line 6, in <module>
    from .app import LabServerApp
  File "C:\Users\evaji\anaconda3\envs\keypoint_moseq\lib\site-packages\jupyterlab_server\app.py", line 15, in <module>
    from .handlers import LabConfig, add_handlers
  File "C:\Users\evaji\anaconda3\envs\keypoint_moseq\lib\site-packages\jupyterlab_server\handlers.py", line 21, in <module>
    from .listings_handler import ListingsHandler, fetch_listings
  File "C:\Users\evaji\anaconda3\envs\keypoint_moseq\lib\site-packages\jupyterlab_server\listings_handler.py", line 10, in <module>
    import requests
  File "C:\Users\evaji\anaconda3\envs\keypoint_moseq\lib\site-packages\requests\__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "C:\Users\evaji\anaconda3\envs\keypoint_moseq\lib\site-packages\requests\exceptions.py", line 9, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "C:\Users\evaji\anaconda3\envs\keypoint_moseq\lib\site-packages\requests\compat.py", line 13, in <module>
    import charset_normalizer as chardet
  File "C:\Users\evaji\anaconda3\envs\keypoint_moseq\lib\site-packages\charset_normalizer\__init__.py", line 23, in <module>
    from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
  File "C:\Users\evaji\anaconda3\envs\keypoint_moseq\lib\site-packages\charset_normalizer\api.py", line 10, in <module>
    from charset_normalizer.md import mess_ratio
  File "charset_normalizer\md.py", line 5, in <module>
    from charset_normalizer.utils import is_punctuation, is_symbol, unicode_range, is_accentuated, is_latin, \
ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant' (C:\Users\evaji\anaconda3\envs\keypoint_moseq\lib\site-packages\charset_normalizer\constant.py)

**Comment by versey-sherry** [comment]
Could you try `pip3 install chardet` in keypoint moseq environment?

**Comment by eva10j** [comment]
It works! Thank you!
