### ISSUE TITLE
ModuleNotFoundError: No module named 'jupyter_bokeh'

### ISSUE THREAD

**Issue by ryanschwark** [dattalab/keypoint-moseq#59]
After launching the most up-to date version of the Keypoint MoSeq Analysis Visualization Notebook, we start with the "Set up notebook for interactive widgets" step. We launched the jupyter notebbok via the Anaconda navigator using the environment called keypoint_moseq. The cell we run has these lines: 

#Install and Enable widget extensions configurator
!jupyter nbextension install --py jupyter_nbextensions_configurator --sys-prefix
!jupyter nbextension enable --py --sys-prefix widgetsnbextension
!jupyter nbextension enable --py --sys-prefix  --py qgrid

#Install bokeh extensions
!jupyter nbextension install --sys-prefix --symlink --py jupyter_bokeh
!jupyter nbextension enable jupyter_bokeh --py --sys-prefix

However, when we run this cell, we get the following error message:

Traceback (most recent call last):
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\Scripts\jupyter-nbextension.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\jupyter_core\application.py", line 277, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\traitlets\config\application.py", line 1043, in launch_instance
    app.start()
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 972, in start
    super().start()
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\jupyter_core\application.py", line 266, in start
    self.subapp.start()
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 702, in start
    self.install_extensions()
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 675, in install_extensions
    full_dests = install(self.extra_args[0],
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 203, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 1107, in _get_nbextension_metadata
    m = import_item(module)
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\traitlets\utils\importstring.py", line 38, in import_item
    return __import__(parts[0])
ModuleNotFoundError: No module named 'jupyter_nbextensions_configurator'
Traceback (most recent call last):
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\Scripts\jupyter-nbextension.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\jupyter_core\application.py", line 277, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\traitlets\config\application.py", line 1043, in launch_instance
    app.start()
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 972, in start
    super().start()
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\jupyter_core\application.py", line 266, in start
    self.subapp.start()
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 882, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 855, in toggle_nbextension_python
    return toggle(module,
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 470, in enable_nbextension_python
    return _set_nbextension_state_python(True, module, user, sys_prefix,
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 368, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 1107, in _get_nbextension_metadata
    m = import_item(module)
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\traitlets\utils\importstring.py", line 38, in import_item
    return __import__(parts[0])
ModuleNotFoundError: No module named 'widgetsnbextension'
Traceback (most recent call last):
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\Scripts\jupyter-nbextension.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\jupyter_core\application.py", line 277, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\traitlets\config\application.py", line 1043, in launch_instance
    app.start()
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 972, in start
    super().start()
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\jupyter_core\application.py", line 266, in start
    self.subapp.start()
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 882, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 855, in toggle_nbextension_python
    return toggle(module,
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 470, in enable_nbextension_python
    return _set_nbextension_state_python(True, module, user, sys_prefix,
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 368, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 1107, in _get_nbextension_metadata
    m = import_item(module)
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\traitlets\utils\importstring.py", line 38, in import_item
    return __import__(parts[0])
ModuleNotFoundError: No module named 'qgrid'
Traceback (most recent call last):
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\Scripts\jupyter-nbextension.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\jupyter_core\application.py", line 277, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\traitlets\config\application.py", line 1043, in launch_instance
    app.start()
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 972, in start
    super().start()
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\jupyter_core\application.py", line 266, in start
    self.subapp.start()
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 702, in start
    self.install_extensions()
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 675, in install_extensions
    full_dests = install(self.extra_args[0],
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 203, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 1107, in _get_nbextension_metadata
    m = import_item(module)
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\traitlets\utils\importstring.py", line 38, in import_item
    return __import__(parts[0])
ModuleNotFoundError: No module named 'jupyter_bokeh'
Traceback (most recent call last):
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\Scripts\jupyter-nbextension.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\jupyter_core\application.py", line 277, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\traitlets\config\application.py", line 1043, in launch_instance
    app.start()
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 972, in start
    super().start()
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\jupyter_core\application.py", line 266, in start
    self.subapp.start()
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 882, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 855, in toggle_nbextension_python
    return toggle(module,
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 470, in enable_nbextension_python
    return _set_nbextension_state_python(True, module, user, sys_prefix,
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 368, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\notebook\nbextensions.py", line 1107, in _get_nbextension_metadata
    m = import_item(module)
  File "C:\Users\Abdus-saboor\miniconda3\envs\keypoint_moseq\lib\site-packages\traitlets\utils\importstring.py", line 38, in import_item
    return __import__(parts[0])
ModuleNotFoundError: No module named 'jupyter_bokeh'

What might be causing this issue? Thanks!

**Comment by calebweinreb** [comment]
We are planning to change this step slightly. Try running those lines (without the exclamation marks) in a command terminal with the keypoint_moseq environment activated. Then after they run, start a jupyter notebook server. Once this notebook is open again, you can skip those lines.

**Comment by calebweinreb** [comment]
What steps did you take to install the branch with the analysis? I ask because `jupyter_nbextensions_configurator` is [listed in the requirements](https://github.com/dattalab/keypoint-moseq/blob/c8e9f070117b23f090557fcfe9c8c008fa82fa78/setup.cfg#L29), so it should have been installed. Just to be sure, these are the steps:
```
conda activate keypoint_moseq
pip install -U git+https://github.com/dattalab/keypoint-moseq@sherry_updates
```

**Comment by ryanschwark** [comment]
Thanks Caleb! It looks like for whatever reason I didn't have the jupyter_nbextensions_configurator installed. After installing by running the lines of code above, it fixed the issue!
